### ISSUE TITLE
1.6.4 Board manager not working for RFDuino (1.6.3 is)

### ISSUE THREAD

**Issue by ybotman** [RFduino/RFduino#23]
Directions says :Download [Arduino 1.6.3](http://arduino.cc/en/Main/Software) on newer.

**Comment by sakrist** [comment]
@ybotman I had the same. You can get previous arduino IDE [here](http://www.arduino.cc/en/Main/OldSoftwareReleases#previous).

**Comment by pierrotm777** [comment]
json file return me an java issue when i use the board manager with IDE 1.6.4.

**Comment by jrobeson** [comment]
this seems to be due to the java http client in arduino 1.6.4 not following a 302 redirect.

**Comment by pierrotm777** [comment]
I have deletes json file and all old downloaded files and it's ok now for me !

**Comment by truedat101** [comment]
Some more details are helpful, as I believe this is the error, seen both on 1.6.4 (Win) and 1.6.5 (Lin).  The work around for users is to first download Arduino SAM Boards (32-bits ARM Cortex-M3) which will get the problematic gcc-arm-none-eabi compilers, and then after it completes, download the RFDuino successfully.

```
Error downloading http://arduino.cc/download.php?f=/gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
java.lang.RuntimeException: java.lang.Exception: Error downloading http://arduino.cc/download.php?f=/gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$4.run(ContributionManagerUI.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://arduino.cc/download.php?f=/gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:100)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:63)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:112)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$4.run(ContributionManagerUI.java:176)
	... 1 more
Caused by: java.io.IOException: Recevied invalid http status code from server: 302
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:160)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:98)
	... 4 more
```

**Comment by funjon** [comment]
Or, go to the direct URL. The Arduino.app package_index.json has the correct url:

fuezakyuu:Arduino.app root# grep -ir gcc-arm-none-eabi-4.8.3-2014q1-mac.tar.gz *
Contents/Java/dist/package_index.json:              "url": "http://downloads.arduino.cc/gcc-arm-none-eabi-4.8.3-2014q1-mac.tar.gz",
Contents/Java/dist/package_index.json:              "archiveFileName": "gcc-arm-none-eabi-4.8.3-2014q1-mac.tar.gz",

Don't hit download.php, the downloader can't handle 302's (which is another, bigger bug).

**Comment by SamDecrock** [comment]
Same problem on Arduino 1.6.4.

Resolved it by first downloading "Arduino SAM Boards (32-bits ARM Cortex-M3)" as @truedat101 mentioned.

Thanks!

**Comment by christopherdro** [comment]
:+1: @truedat101

**Comment by brycejones** [comment]
thank you @truedat101 .Your recommendation solved my issue with Arduino IDE 1.6.5.
 "The work around for users is to first download Arduino SAM Boards (32-bits ARM Cortex-M3)"
